# SITE CONFIGURATION
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://example.com" # the base hostname & protocol for your site

# THEME-SPECIFIC CONFIGURATION
theme_settings:
  # Meta
  title: "Materialize CSS Theme"
  avatar:
  gravatar: # Email MD5 hash
  description: "Website of Materialize CSS Theme." # used by search engines

  # Header and footer text
  header_text:
   <p>Welcome your new thought leader:Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
   <p>Remove all header text in <code>_config.yml</code> to disable this feature.</p>

  header_text_feature_image:
  footer_text: true

  # Icons
  rss:
  email_address: # Full email address, e.g. "sam@example.com"
  behance:
  bitbucket:
  dribbble:
  facebook:
  flickr:
  github: "calebomusic"
  google_plus:
  instagram:
  linkedin: https://www.linkedin.com/in/caleb-ontiveros
  pinterest:
  reddit:
  soundcloud:
  stack_exchange:  # Full URL
  steam:
  tumblr:
  twitter: "cleboomusic"
  wordpress:
  youtube:

  # Scripts
  google_analytics: # Tracking ID, e.g. "UA-000000-01"

  # Localization strings
  str_follow_on: "Follow on"
  str_rss_follow: "Follow RSS feed"
  str_email: "Email"
  str_next: "Next"
  str_prev: "Previous"
  str_continue_reading: "Continue reading"

  # Colours, typography and padding
  # Open the "_sass > base" folder, and open "_variables.scss"
  google_fonts: "Dosis:400,700|Source+Sans+Pro:400,700,700italic,400italic"
  katex: true # Enable if using math markup

  # Post navigation
  post_navigation: true

# PAGINATION
paginate: 3
paginate_path: "blog/page:num"

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
